<!-- INICIO: Contenedor principal -->
					<div class="container">

						<!-- INICIO: Fila -->
						<div class="row">

							<!-- INICIO: Columna 1 -->
							<?php include("L1_P2_2/html/menu_p2_2.html"); ?>
							<!-- FIN: Columna 1 -->

							<!-- INICIO: Columna 2 -->
							<?php include("L1_P2_2/html/formp2_2.html"); ?>
							<!-- FIN: Columna 2 -->
						</div>
						<!-- FIN: Fila -->

					</div>
					<!-- FIN: Contenedor principal -->


					<div class="container-fluid"> <!-- INICIA CONTENEDOR-->
						
					</div> <!-- TERMINA CONTENEDOR-->